### ISSUE TITLE
Remove push_to_pulp

### ISSUE THREAD

**Issue by Zyzyx** [release-engineering/dockpulp#15]
A fair bit of atomic-reactor logic exists in this call and command. It should really live in atomic reactor, not dockpulp.

**Comment by TomasTomecek** [comment]
I would prefer if dockpulp mimic docker's push behavior: you specify image and tag under it should be available in the remote repository. I feel like that all the `upload`, `copy`, `createRepo`, `updateRepo` commands are specific to pulp and should _not_ live in reactor. Or do you want dockpulp to be wrapper on top of pulp's api without any logic?

**Comment by Zyzyx** [comment]
My original design was just to be a wrapper that hid Pulp complexities as needed to make interacting with it simpler. We use it for pushing to internal registries too. (qa, stage and production)

I'm ok with making the upload command more docker-like, even having *push* synonym. I'm against putting atomic specific logic into the API though. The push_tar_to_pulp method contains logic for creating missing repositories on demand and sets attributes on them based on 2 passed in values, one of which is a dictionary-of-dictionaries. I don't consider that a good interface.

The better way to do this is to have reactor figure out which repositories are missing, and call createRepo with the right values instead for each missing one. I admit this was not easily done before the exists() method was written. That's why I added that after I saw the PR come in.

The push_to_pulp command in the CLI is a problem. Anyone looking at the help will see upload and push_to_pulp and it isn't clear which one is the correct choice. Only one of them checks that the tarballs are acceptable pulp. The command makes things convenient for the new OSBS deployment at the expense of clarity for RCM pushing images to customers. There should only be one way to push images around.

**Comment by TomasTomecek** [comment]
Okay, I'm fine with having this logic in reactor:
```python
if not pulp.exists(repo):
    pulp.create_repo(repo)
pulp.upload(repo, image, tags)
```

Where upload puts the image to proper repository and applies all tags to the image (and removes former duplicate ones).

**Comment by TomasTomecek** [comment]
I think it's safe to remove the method now, since we are about to move it to [atomic-reactor](https://github.com/projectatomic/atomic-reactor/pull/367).

**Comment by breillyrh** [comment]
Dockpulp no longer has push_to_pulp nor push_tar_to_pulp.
