### ISSUE TITLE
provide a way to set cert and key via API

### ISSUE THREAD

**Issue by TomasTomecek** [release-engineering/dockpulp#21]
In order to migrate to upstream dockpulp, atomic-reactor is using `set_certs()` method. We have certificate data at specific path (provided by openshift as a secret), so we just need to pass them to dockpulp. Here's the implementation of the method: https://github.com/midnightercz/dockpulp/blob/49211164f2880c3b620932a079b9514686563956/dockpulp/__init__.py#L682

**Comment by twaugh** [comment]
Fixed via https://github.com/release-engineering/dockpulp/pull/24.

**Comment by TomasTomecek** [comment]
Closing then.
