### ISSUE TITLE
dockpulp messes up logging of tools which import it via python

### ISSUE THREAD

**Issue by TomasTomecek** [release-engineering/dockpulp#33]
[This](https://github.com/release-engineering/dockpulp/commit/654db75f05c8f3197a7da55ad2603a10955d749f#diff-9ba87aa0393270cd6970103304a831acR58) is the problematic line:

```python
logging.basicConfig(stream=sys.stdout, format='%(levelname)-9s %(message)s')
```

It means that you are setting up a root logger which is really weird b/c two lines above there is another logger set up:

```python
log = logging.getLogger("dockpulp")
```

Please, set up the handler for `log` in `bin/dock-pulp.py`. That way you'll have logs when calling dockpulp from CLI and at the same time, atomic-reactor won't have double-logs:

```
2015-11-26 07:06:04,956 - atomic_reactor.plugin - DEBUG - running plugin 'tag_by_labels'
DEBUG     running plugin 'tag_by_labels'
2015-11-26 07:06:04,956 - atomic_reactor.plugin - INFO - running plugin instance with args: '{}'
INFO      running plugin instance with args: '{}'
2015-11-26 07:06:04,956 - atomic_reactor.plugin - DEBUG - running plugin 'tag_and_push'
DEBUG     running plugin 'tag_and_push'
```

Last logging patch was provided by @pbabinca https://github.com/release-engineering/dockpulp/commit/e4eeed2f6febda6e40fa72ee1a2f1d39149555aa

**Comment by breillyrh** [comment]
Issue resolved by [commit](https://github.com/release-engineering/dockpulp/commit/97ea7e8e7494db3e1fa2ffa0c0dd0e6c6ed44233).

**Comment by TomasTomecek** [comment]
Thanks Brendan; this should do the trick.
