### ISSUE TITLE
syncRepo cannot sync from https:// registry feed

### ISSUE THREAD

**Issue by twaugh** [release-engineering/dockpulp#47]
This code is wrong:

```
        if syncenv.startswith("https"):
            syncenv = syncenv.replace("https","http")
```

https://github.com/release-engineering/dockpulp/blob/master/dockpulp/__init__.py#L754

Whatever is in the config should be used as-is, without changing port numbers or schemes.

**Comment by twaugh** [comment]
It was introduced in e2ea709f76976b444fcb4ed398425d5fec2b5eb4.

**Comment by breillyrh** [comment]
Will need to double check with jluza on this change, if I remember correctly, sync requires http instead of https, and it uses the [pulps] section from dockpulp.conf. Worst case scenario we are going to need another section in the conf.
