### ISSUE TITLE
Provide a way to discover the default prefix

### ISSUE THREAD

**Issue by twaugh** [release-engineering/dockpulp#56]
dockpulp adds a default prefix to repo IDs, but callers have no way to find out what it is.

This is a problem when it comes to e.g. creating repositories on demand, because the straightforward route doesn't work:

1. Ask for list of existing repo IDs
2. Look through the list for the one we need
3. If not in the list, create it

This is because the list of existing repo IDs (`getRepos([...], fields=["id"])`) includes the prefix, but the repo id we know we want to create does not.

One solution would be for dockpulp to have a global PREFIX variable, so callers could inspect that. Now the solution to creating on demand becomes:

1. Prefix the repo ID we have with dockpulp.PREFIX
2. Look for that repo ID
3. If not found, create it

**Comment by breillyrh** [comment]
Added in https://github.com/release-engineering/dockpulp/commit/60e27193615428a663b42d258ca7b26afa15e388
