### ISSUE TITLE
"list -c" does not indicate which manifest is 'current' for each tag

### ISSUE THREAD

**Issue by twaugh** [release-engineering/dockpulp#81]
Multiple manifests with the same tag can be in a repository at once.

e.g.
```
INFO        Manifest: sha256:cd389be776c0aa921d701c43da6936119462b7d8630d38949eddc38350ea81ea  Tag: 9.0-5
INFO        Manifest: sha256:6fec0a094498c57db2ba6f8fa2e6ca3a15d8dd0c1a37cb92223cb8a63aef027e  Tag: 9.0
INFO        Manifest: sha256:cefc1a3a1c95f87f7a4cb565892269ed6522e0f9d050e2461710f5adc061a1fc  Tag: latest
INFO          Blobs:
INFO            sha256:dc5a58406743f99bb216ce40ff4135702b3211b4ab8fccb8c8b28e3987c8b1fd
INFO            sha256:ee4aeaf2fc2de851c2007f19a50458de82918c8b1913b9145de643ecb183e82b
INFO      
INFO        Manifest: sha256:f02ee398fccca7391f985ce823e271258dca4ed55bfca0e7825b03211d7360b7  Tag: 9.0-6
INFO        Manifest: sha256:29dde9288c706e37c80211f4ef84bc2e06c25fbb6a4814fa03c3a80770066f55  Tag: latest
INFO        Manifest: sha256:6b580c259abaa96b0fdcdfad140fc4ca628445ba038b57691f2608a065886295  Tag: 9.0
INFO          Blobs:
INFO            sha256:5fbcecc69f479b30e2ae9b1992349b0f0f07a466b341e11c5f07076c67565fd4
INFO            sha256:ee4aeaf2fc2de851c2007f19a50458de82918c8b1913b9145de643ecb183e82b
```

There will be a docker_tag unit in that repository for each unique tag. We should use those to indicate which manifest is current for each tag.

**Comment by breillyrh** [comment]
Those old manifests still exist though, so should list just not show the outdated manifests?

**Comment by twaugh** [comment]
In the example above, there are two manifests for 'latest':

- sha256:cefc1a3a1c95f87f7a4cb565892269ed6522e0f9d050e2461710f5adc061a1fc
- sha256:29dde9288c706e37c80211f4ef84bc2e06c25fbb6a4814fa03c3a80770066f55 (which is newer, and most likely the docker_tag unit will be referencing this manifest)

The first one will still be reachable in crane by its manifest digest, e.g.
- docker pull $REGISTRY/$REPOSITORY@sha256:cefc1a3....

The second will will be reachable in crane by both its manifest digest and its tag, e.g
- docker pull $REGISTRY/$REPOSITORY@sha256:29dde928...
- docker pull $REGISTRY/$REPOSITORY:latest

**Comment by breillyrh** [comment]
So in the case of the first manifest, should list just display the manifest without tag information?

**Comment by twaugh** [comment]
That probably makes the most sense.

**Comment by twaugh** [comment]
Actually, no, it should report tag names for manifests that are not reachable by their tag. But it should mark the currently 'active' manifest for a tag specially, maybe something like this:

```
INFO        Manifest: sha256:...  Tag: 9.0-5 (active)
INFO        Manifest: sha256:...  Tag: 9.0
INFO        Manifest: sha256:...  Tag: latest
[...]
INFO        Manifest: sha256:...  Tag: 9.0-6 (active)
INFO        Manifest: sha256:...  Tag: latest (active)
INFO        Manifest: sha256:...  Tag: 9.0 (active)
```

The reason for continuing to report tag names for manifests whose tags are not reachable is that the user will have some idea of what it relates to. It would also make it easier to change which manifest is active for a tag if this upstream Pulp feature is implemented:
https://pulp.plan.io/issues/2189

**Comment by breillyrh** [comment]
Added in this PR https://github.com/release-engineering/dockpulp/pull/85/files
